### ISSUE TITLE
Failure to parse cwl_format.cwl

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/heterodon#3]
Trying to salad file https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl: 

Using heterodon:
```
INFO  - Pre-Processing https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl
Failed to run cwltool on file https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl#main (reason 1 of 1): Traceback (most recent call last):
  File "/Users/chrisl/Library/Caches/Coursier/v1/https/broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/heterodon/1.0.0-beta2/heterodon-1.0.0-beta2-single.jar/Lib/heterodon/__init__.py", line 24, in apply
  File "<string>", line 1, in <module>
  File "<string>", line 12, in cwltool_salad
  File "/Users/chrisl/Library/Caches/Coursier/v1/https/broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/heterodon/1.0.0-beta2/heterodon-1.0.0-beta2-single.jar/Lib/cwltool/load_tool.py", line 279, in validate_document
  File "/Users/chrisl/Library/Caches/Coursier/v1/https/broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/heterodon/1.0.0-beta2/heterodon-1.0.0-beta2-single.jar/Lib/schema_salad/ref_resolver.py", line 841, in resolve_all
  File "/Users/chrisl/Library/Caches/Coursier/v1/https/broadinstitute.jfrog.io/broadinstitute/libs-release/org/broadinstitute/heterodon/1.0.0-beta2/heterodon-1.0.0-beta2-single.jar/Lib/schema_salad/ref_resolver.py", line 402, in add_schemas
UnboundLocalError: local variable 'fetchurl' referenced before assignment
```

Using command line `cwltool`:
```
#> cwltool --print-pre https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl

/usr/local/bin/cwltool 1.0.20170501141222
[
    {
        "id": "https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl#main",
        "class": "CommandLineTool",
        "cwlVersion": "v1.0",
        "inputs": [
            {
                "id": "https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl#main/reference",
                "type": "File",
                "format": "http://galaxyproject.org/formats/fasta",
                "inputBinding": {
                    "position": 2
                }
            }
        ],
        "outputs": [
            {
                "id": "https://raw.githubusercontent.com/broadinstitute/cromwell/develop/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl#main/lineCount",
                "type": "int",
                "outputBinding": {
                    "glob": "stdout",
                    "loadContents": true,
                    "outputEval": "$(parseInt(self[0].contents))"
                }
            }
        ],
        "baseCommand": [
            "wc",
            "-l"
        ],
        "stdout": "stdout"
    }
```

**Comment by kshakir** [comment]
Works as expected?

Heterodon currently pins cwltool at the more up-to-date [`1.0.20180809224403`](https://github.com/broadinstitute/heterodon/blob/f4ad47d3cb93db189271007820e88194e525e334/setup.py#L7).

Running that version, versus the above `1.0.20170501141222`, produces the same error.

```shell
$ pip -q install --upgrade --force-reinstall cwltool==1.0.20180809224403 && cwltool --print-pre https://raw.githubusercontent.com/broadinstitute/cromwell/db44ea34238a3f16ad365f7527694e23b028f758/centaur/src/main/resources/standardTestCases/cwl_format/cwl_format.cwl
/Users/kshakir/.virtualenvs/cwltool/bin/cwltool 1.0.20180809224403
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: local variable 'fetchurl' referenced before assignment
$ 
```

I have no idea what that error means, but it appears to have popped up somewhere between [these two cwltool releases](https://github.com/common-workflow-language/cwltool/compare/1.0.20180211103944...1.0.20180220041300) if you want to follow up over there.

Closing for now, but re-open with a version and a test case if heterodon's jython is not working as cwltool's cpython does.
